### ISSUE TITLE
Add an output in state transitions

### ISSUE THREAD

**Issue by OrangeMagicer** [pnavais/state-machine#1]
Hi, How to add an output in state transition, just like mealy machine.

**Comment by 990123** [comment]
This may not be correct, because the value of output should depend on the input. 
Referring to your approach,  is it possible to define an output property for each input as follows:

```java
State state = new State("s0");
state.addProperty("input1", "output1");
state.addProperty("input2", "output2");
...
```

However, due to the large input space, the above approach will be very troublesome.  

The state machine we want to represent looks like this:

![Mealy Machine](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRZjOeWbUSbyMpKYkhbcWcAjxpSGEClzSOUw&usqp=CAU)

 if there is a better solution, please let me know, thanks!
